- hosts: production
  become: true
  tasks:
    - name: Navigate to directory containing docker-compose.yml
      shell: cd devops assessment
      args:
        chdir: /home/ec2-user/debug-test

    - name: Run docker-compose 
      shell: docker-compose up -d
      args:
        chdir: /home/ec2-user/devops-assessment